### ISSUE TITLE
Try port 9595 for LMS on Zyxel NAS devices

### ISSUE THREAD

**Issue by jojojojojojo** [nikclayton/android-squeezer#135]
Running
Logitech Media Server Version: 7.7.1 - r33735 @ Mon Nov 28 16:49:58 MST 2011
(unfortunately the newest version offered for my Zyxel NSA325-v2 NAS)
I cannot connect with Squeezer.
When scanning, it does find the server (192.168.2.100:9090). I have to change the port to 9000, otherwise the connection does not work at all. When changing to 9000, I get the message
"Login failed. Make sure the correct port, user name and password is entered"
Entering 192.168.2.100:9000 in the Chrome Browser of my stock android 5 mobile (on which I also want to use Squeezer), it works, the server-page is shown.
Is that an issue with the old LMS server?
Kind regards

**Comment by kaaholst** [comment]
The 9000 is most probably the HTTP-port. When you try to connect to the HTTP-port the server will disconnect, and you will get "Login failed".

Squeezer requires the CLI (Command Line Interface) port to connect successfully.

You can check the HTTP port by connecting to the LMS web interface, select settings, select the advanced tab, and select network from the dropdown.

The CLI-port can be viewed by instead selecting "Command Line Interface" from the dropdown. The default value for the CLI-port is 9090, so Squeezer will attempt that by default.

If LMS is password protected, you have to enter username and password on the Squeezer login page. LMS username and password is viewed by selecting "Security" from the dropdown.

I am not aware of any problem with LMS version 7.7.1.

Hope this helps, otherwise please report back.

**Comment by jojojojojojo** [comment]
Hello,
thanks for the quick reply!
In my LMS version I dont have the http port listed in advanced settings, unfortunately also not the CLI in the dropdown list.. I guess this is result of buing built to run on the NAS..
Are there othe methods to find out about CLI? I tried to find something in the player settings, but no luck.
Kind regards,
Johannes


![lms_advanced_menu](https://cloud.githubusercontent.com/assets/13542774/8939503/1270e37c-3565-11e5-8d44-13a69c528ceb.jpg)
![lms_advanced_network](https://cloud.githubusercontent.com/assets/13542774/8939502/126cd0ac-3565-11e5-9f86-f6846176a269.jpg)

**Comment by kaaholst** [comment]
I don't know why the settings are missing, maybe, as you say, it's the Zyxel version.

Sometimes connection issues are caused by some setting on the NAS, maybe the port is blocked or used for something else.

Maybe there is an admin-app for LMS on the NAS?

Finally you could look in http://forums.slimdevices.com.

**Comment by jojojojojojo** [comment]
Hello,
I found it, just 2 sec after your post:)
http://forums.slimdevices.com/showthread.php?94510-How-to-enable-CLI-on-Zyxel-NSA310&s=99dbc3541c7cf53ab636c79d862b9dc9
So the CLI port on Zyxel NAS is 9595. Working brilliantly now:-)
Thanks again,
regards

**Comment by nikclayton** [comment]
Thanks for the info. I'll prep a change that adds 9595 to the list of ports that Squeezer tries if no port is specified.

**Comment by jojojojojojo** [comment]
Hello Nik,
you're welcome! Glad I could help a bit:)
I now have an issue that squeezer doesnt see my library on my local LMS.
But I will first try to reinstall and see if the problem still exists.
Regards,
Johannes


2015-08-09 7:56 GMT+02:00 Nik Clayton <notifications@github.com>:

**Comment by kaaholst** [comment]
I’m closing this issue because it has been inactive for a few years.

Please create a new [issue](https://github.com/kaaholst/android-squeezer/issues) if you still request this. 

Thank you!
