### ISSUE TITLE
Unable to download from server

### ISSUE THREAD

**Issue by tobukikai** [nikclayton/android-squeezer#143]
I have Squeezer running on a Samsung S4.  Most of my music is in FLAC format and so around 20MB per song.  When i select to download, the Android Downloader native app starts, and shows the download bar cycling through (not a bar that shows percent downloaded, but one as if it is connecting).  It never does download, and eventually closes the download notification.  Sometimes the download appears again randomly, as if it is still trying to download.

i might be able to test access to the music, but don't know what URL Squeezer gives for doing the download.

**Comment by kaaholst** [comment]
To obtain the url Squeezer use for download, you can enter the web-interface of of your Logitech Media Server. 

Select My Music from the main menu, select Albums and select any album. Then select any song (click the link on the name of the song). The link on the location field, is (almost) the URL Squeezer uses to download the song.
It looks like this:
http://192.168.0.13:9001/music/21774/download/02.%20Adele%20-%20Rumour%20Has%20It.flac

The URL Squeezer uses is the same, except with the name part omitted, i.e. it ends with "download".

To test the download, e.g. mail the download-link to yourself, open the mail on your phone, press the download-link and the download should start.

Hope this helps, otherwise please report back.

**Comment by tobukikai** [comment]
Finally getting back to this.  Sorry for the delay.
Thanks for the suggestion Kurt, I hadn't known about this. What I found 
is that i can't download any of my music from my server at all.  So 
something must be wrong with my installation and I'm pretty certain this 
isn't an issue with Squeezer.

Can't find much info on troubleshooting LMS, so I'm thinking of moving 
over to Kodi..
