### ISSUE TITLE
can't do search directly from 'Now playing'

### ISSUE THREAD

**Issue by tbrandysky** [nikclayton/android-squeezer#152]
I would like to see some possibility to perform a search for Interpret or Album or other items directly from context menu of currently playing song.

This feature is available in other squeezebox controlling apps as well as LMS web interface (click on any song in current playlist -> click on Interpret or Album link)

This comes in handy when streaming from Spotify or Deezer.

**Comment by kaaholst** [comment]
I'm sorry I can't seem to find this on the LMS web interface. Could you please tell me which version of the server you use, and post a screen shot showing the requested functionality.

**Comment by tbrandysky** [comment]
Hello,

tested on Logitech Media Server Version: 7.8.0 - 1395409907 as well as 7.9 LMS

screen1:
http://shamot.cz/~shamot/upload/LMS/song_info_1.png

when I click to any song in Playlist I get the song info to left frame.

see "Artist: Tommy Tokyo" in the left frame. 
Tommy Tokyo is a clickable link which performs a search on this artists and gives me all albums from this artist -> see screenshot2

screen2: 
http://shamot.cz/~shamot/upload/LMS/song_info_2.png

The same works when streaming music from Spotify excepts it lists all artist's albums on spotify and not local music.

Thank you

Tomas

**Comment by kaaholst** [comment]
OK, now I understand, thanks for info and the screenshots.

Currently in Squeezer you can search for song on album and albums or songs by artist from the context menu of songs in the current playlist. You get the context menu from the little triangle to the right of each song, or by long pressing a song.

As for Spotify and Deezer, our support for 3'rd party apps is currently limited due to the situation described here: https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer.

**Comment by kaaholst** [comment]
Fixed in 2.0.0
