### ISSUE TITLE
Feature request: confirmation dialog for 'remove current playlist' button

### ISSUE THREAD

**Issue by zordaz** [nikclayton/android-squeezer#158]
It is very easy to accidently remove the current playlist because there is no confirmation dialog implemented.

**Comment by orclex** [comment]
I agree to that! Also if you accidently click on "play song" instead of "add to playlist" you overwrite the current playlist too. Maybe it would be great to always temporarily save the previous playlist and to have a button to revert to the previous playlist?

**Comment by kaaholst** [comment]
Fixed in 2.0.0

**Comment by zordaz** [comment]
In the latest version of Squeezer (2.2.0) the confirmation option dissapearred. Is it possible to reopen this request?

**Comment by kaaholst** [comment]
You are quite right, in the latest version "remove current playlist" is handled by the app. In the previous version it was handled by the Logitech Media Server which had a confirmation dialog.
I forgot about this request when making that change, so it is now reopened. 
There will be confirmation dialog in the next version.

**Comment by kaaholst** [comment]
This is fixed in Squeezer version 2.2.1 and newer, closing.

**Comment by zordaz** [comment]
I can understand why the original bug is considered as 'closed'. The implementation is in my opinion however confusing, because it is not a confirmation button which is implemented but an 'undo' button with a delay. The playlist is still deleted automatically after a few seconds, so it is also still possible to accidentally hitting the delete icon without noticing and losing your playlist.

**Comment by kaaholst** [comment]
Yes technically speaking this isn't resolved as there is no confirmation dialog. The reason I went for an undo solution is because some human interface guidelines recommend avoiding unnecessary confirmation dialogs e.g:
https://goodui.org/#8
https://designsmarts.co/confirm-or-undo/
https://alistapart.com/article/neveruseawarning/

Having said that there are also many guides which recommend  confirmation dialogs and many people like them. Furthermore there is no technical issues to not provide an (optional) undo button post confirmation. 

I reopen this, please comment if you prefer a confirmation dialog.

**Comment by kaaholst** [comment]
In 2.2.2 we have a (optional) confirmation dialog, so closing this.

**Comment by zordaz** [comment]
Thanks. The implementation is fine now imho.
