### ISSUE TITLE
List only Album artists?

### ISSUE THREAD

**Issue by cw-kid** [nikclayton/android-squeezer#289]
Hi

Nice app only thing when I go in to Artists it is also listing all the artists off my compilation albums.

I don't want to see these artists listed but for it to only display Album Artists.

Couldn't see anyway to change this?

Thanks

**Comment by jepzen** [comment]
Totally agree with that. Album artist is way more nice to have

**Comment by kaaholst** [comment]
Hi, 

Recent servers support two browse modes for Album Artists and All Artists instead of one single list. Squeezer doesn't support that yet. In the mean time you may try setting the browse mode to: "Use single, configurable list of artists", it may be closer to what you want. The setting is found via the LMS web interface, choose the "My Music" tab.

**Comment by kaaholst** [comment]
Fixed in 2.0.0
