### ISSUE TITLE
Totally unusable since the latest release

### ISSUE THREAD

**Issue by PatrickHonorez** [nikclayton/android-squeezer#534]
No device visible. I can locate the server, play a song, but where does it play ? No clue and I can't hear it. No device means no alarm settings. Not to mention the fact that the app never closes unless I kill it from Settings/Applications.
This is a terrible release. How can I get the previous one ?

**Comment by kaaholst** [comment]
Thanks for creating an issue on github.

How Squeezer finds and shows devices (players) has not been changed in the latest releases.
I can describe how it generally works, and if that doesn't help, please report back.
Squeezer connects to the server and retrieves the connected players from the server and subscribes to changes to that list.
These devices are shown as a drop-down list in the top left of the display. You can select which player to control (and show on the now playing screen/bottom bar), by selecting it in the drop-down. If the server returns only one player, there won't be a drop-down, instead Squeezer shows the name (as reported by the server) of the player. If the server reports no players we show "Squeezer" instead of a player name.

Regarding the visible notification, it's a requirement in the latest Android versions. Up until now Squeezer had an option to display a notification while connected. Since it is now required to show a notification, this is no longer optional.

To turn off the notification, tap the notification, select the options menu (the three dots in the top right corner), select Disconnect. This removes the notification until next time Squeezer connects.
To disable notifications for the Squeezer app, do it via the [Android Settings App](https://support.google.com/android/answer/9079661?hl=en#)

The reasoning behind the requirement is that the user is aware that an app is using system resources even, if it is not visible.

Squeezer works by connecting to a server to retrieve state about the server and the players which are connected to the server. Because creating the connection is a costly operation, and to avoid going to the "Home screen", after each break, we keep the connection open. When Squeezer is not visible subscriptions for events from the server is kept to a minimum, so we should not use much battery, but we still use memory. In that respect the Android requirement makes sense, as many users probably aren't aware of that.

Here is an example of what [Android says about it (developer documentation)](https://developer.android.com/guide/components/services#Foreground)

**Comment by PatrickHonorez** [comment]
Hi kaalholst,

Thanks for your reply. Sorry I did not update the status earlier.
I solved the "unusable" part by going to Settings/Apps and Notifications/Select Squeezer/Storage/**Erase data**.
Then I reopened the app and all was back OK, including devices and...alarm :-)

Regarding the notification, I don't care about having one. The problem is that when I close Squeeze, the the notification is still there? Even when I swipe up Squeezer from the recent apps list, the notification remains. I really have to kill the app for the notification to go away. Is there a timeout after which Squeezer closes ?

**Comment by mklemme1** [comment]
I also have an issue with the notification. 

I start Squeezer
I switch off my Squeezebox using the app
There is nothing left to do for Squeezer. 
But there is no "quit" menu action in the app, and I cannot slide out the notification to quit the App. 

Regards
  Michael

**Comment by kaaholst** [comment]
@PatrickHonorez The display issue on the alarms screen will be fixed in the upcoming ["JSON" release.](https://github.com/nikclayton/android-squeezer/wiki/Apps-support-in-Squeezer). This will also update the display more consistent when player is changed.

@mklemme1 To remove the notification select the "Disconnect" menu action. 
There is no "Quit" option in Squeezer because Android doesn't really work that way.The idea is that Android itself closes inactive apps when it needs resources. To avoid having to reconnect and go to the Home screen, we tell Android not to close Squeezer as long as we are connected to a server. What's new is that we are now required to show a notification. Unfortunately this also means that the notification cannot be swiped away. I was expecting that functionality myself.

What we can do is:
1. Disconnect Squeezer (and remove the notification) when Squeezer is swiped from the recent apps screen.
2. Have a button on the notification to disconnect
3. Implement a timeout after which Squeezer closes

**Comment by mklemme1** [comment]
Thanks for explaining.
(1) would be my favourite.

**Comment by PatrickHonorez** [comment]
Hi Nick,

Thanks for your reply and for the good news.
If I had to choose, I would very well see a small x cross on the
notification (option 2), like what we see for most music apps like Spotify,
youtube, etc...
But ideally I think all 3 options are useful and not mutually exclusive  :-)

Regards,
Patrick
+352 691-67-68-65

**Comment by PatrickHonorez** [comment]
You are right, most apps just allow swiping the notification. Anyway I
found an example of 'x', but swiping is probably more standard today.

Regards,

Patrick

Le mer. 16 oct. 2019 à 09:36, Kurt Aaholst <notifications@github.com> a
écrit :

**Comment by mklemme1** [comment]
BubbleUPNP has an "x" in the notification to close the app. 
But I still think swiping us more intuitive. 

Am 16. Oktober 2019 09:36:25 MESZ schrieb Kurt Aaholst <notifications@github.com>:

**Comment by mklemme1** [comment]
I got a new version 1.5.4 from the regular store. 
The "x" button works for me, thanks!
Sliding the notification left or right does not remove it.

Thanks

**Comment by PatrickHonorez** [comment]
The display issue seems to be still there on my Pixel 3.

Patrick

Le lun. 14 oct. 2019 à 18:50, Kurt Aaholst <notifications@github.com> a
écrit :

**Comment by kaaholst** [comment]
@mklemme1 Sliding the notification to remove is unfortunately not possible. Squeezer will disconnect when it's swiped from recent apps. If "recent apps" doesn't mean anything to you, please report back :-) 

@PatrickHonorez The display issue is fixed in later release, which I'm working to make ready to be released. It's changes the protocol that Squeezer uses to communicate with the server. This protocol works fundamentally different, so it's a major rewrite of Squeezer and therefore needs substantial testing to make sure it's ready for release.

**Comment by PatrickHonorez** [comment]
Good news. Thanks ofr the energy you put in that app !!

Patrick
