### ISSUE TITLE
New beta does not connect to server

### ISSUE THREAD

**Issue by PatrickHonorez** [nikclayton/android-squeezer#611]
Updated to the new 2.0 beta. It is able to scan and identify my server, but it could no cconnect to it. 
I cleared the cache and data and tried again, no change.  
I unistalled, left the beta program, and reinstalled the 1.x version -> no issue (expect the old well known screen refresh issue in the alarm screen).

Sorry if I post in the wrong place. Thx

**Comment by networxnet** [comment]
Same to me. 

Cache clearing --> no success

Additionally icon on desktop got lost with install ob beta.

Is there any chance to contact author directly? Google groups seems to be silent for years ...

**Comment by kaaholst** [comment]
This is the right place to post issues with Squeezer and thanks for posting.

I am sorry that you have problems with the new version.

I have a few questions to help pinpoint the problem.

1. What is the IP-address of device you run Squeezer (probably your phone) (system settings/wifi/menu/advanced)?
2. What is the result of running a scan for servers from squeezer?
3. Can you connect to the scan result from the browser on the same device you run Squeezer?
4. Does the 1.x version display artwork? 
5. Which version of LMS are you running?
6. Is LMS password protected?
7. What does Squeezer say when it doesn't connect?
8. If there is any error message in the server log when Squeezer attempts to connect, then  please send it to me:

Private IP-addresses you can just send as is, otherwise please write like this: "[first IP-number].xx.xx.xx:[port]".
Private IP addresses starts with "192.168.", "172.16-31." or "10." and cannot be routed through the public Internet

Here's how it is supposed to work.

The 1.x version connect to LMS via the CLI protocol on the CLI port. Once connected it retrieves the HTTP port via the CLI protocol, which it uses to download artwork. 

On the 2.0 version, if it is an upgrade we already have the CLI port stored in the settings, so on the first connect it connects via the CLI protocol to learn the HTTP port, which is then used for for all further connects.
Otherwise it connects using the entered HTTP port, or the default port 9000 if none is entered.
If connects via the CometD protocol, so that must be supported on the server.

**Comment by PatrickHonorez** [comment]
Hi, thanks for replying.

my phone IP: 192.168.178.1
The LMS is not password protected, and runs on a Synology NAS.

> Logitech Media Server Version : 7.7.6 - 1452060463 @ Thu Jan 21 02:17:04 UTC 2016
> Nom d'hôte : SynoPat
> Adresse IP du serveur : 192.168.178.26
> Port HTTP du serveur : 9002
> Système d'exploitation : Synology DiskStation - FR - utf8

The new Squeezer version properly detects the server, but fails to connect (msg; "La connexion a échoué, vérifiez les paramètres"). 
However I noticed the old version connects using port 9090 (automatically) and fails if I change port to 9000.
I tried to force port 9090 with the new version, connection fails as well.
The old version does display the images.

**Comment by networxnet** [comment]
Hi Kurt,

and thanks for reply.


>     1. What is the IP-address of the device you run Squeezer (probably your phone) (system settings/wifi/menu/advanced)?
**192.168.200.11** 
>     2. What is the result of running a scan for servers from squeezer?
**Finds LMS at 192.168.200.43**
>     3. Can you connect to the scan result from the browser on the same device you run Squeezer?
**YES** 
>     4. Does the 1.x version display artwork?
**i suppose not??? I use for internet radio most oft the time**
>     5. Which version of LMS are you running?
**7.9.2 - 1576909043 @ Sat Dec 21 07:49:28 CET 2019**
>     6. Is LMS password protected?
**NO**
>     7. What does Squeezer say when it doesn't connect?
**Verbindung fehlgeschlagen. Prüfen Sie die Einstellungen.**
>     8. If there is any error message in the server log when Squeezer attempts to connect, then  please send it to me:

**Comment by kaaholst** [comment]
@PatrickHonorez 
Try to connect to:
192.168.178.26:9002

and I see that the new French translation works :-)

**Comment by kaaholst** [comment]
@networxnet 
Your network and server seems fine, so I'm afraid I need some more info.

1) Does the internet radio stations have artwork?
2) What do you write in the address bar of the browser?
   The result should the Web interface of the LMS, it looks like the screenshot below.

![Screenshot (3  jan  2020 23 21 31)](https://user-images.githubusercontent.com/428304/71753153-f1c37980-2e81-11ea-9b5c-f2d554879bb8.jpg)

**Comment by networxnet** [comment]
Artwork works if radio station is saved in local LMS. If it ist an mysqueezebox favorite Artwork will not ne shown.

See Screenshots attached

**Comment by kaaholst** [comment]
@networxnet  
The screenshots you posted, suggests that you can connect to Squeezer using this:

_192.168.200.40:9001_

Please try this, and report back if it works, thanks.

**Comment by networxnet** [comment]
I'm a bit confused ....

As far as i know 9001 is the LMS default port and the port Squeezer has used before by default. Can you tell why the new version tries to connect port 9000? Or i'm on the wrong path here?

btw connect works with 9001 (y)

**Comment by networxnet** [comment]
i forgot to mention that i like the new layout/desktop *great* :)

**Comment by PatrickHonorez** [comment]
@kaaholst thx, it works perfectly with port 9002 :-)
Very fast 8-D

**Comment by kaaholst** [comment]
Normally the default HTTP port is 9000. On some NAS the default is different e.g. 9001 or 9002. The HTTP port is what the CometD protocol, which the new Squeezer version uses, accepts connections on. It is also the port which accepts connections from a browser (the Web interface), and which Squeezer (old and new versions)  uses to fetch artwork. 

The port which accepts connections on the CLI protocol port is normally 9090. The CLI port does not accept the CometD protocol, so the new Squeezer version will fail on the CLI port.

Since these are updates from an older Squeezer version, the HTTP port should have been known, so there must be a bug. I will fix this and also show some instructions when the connection fails. Actually the current "Connection failed" is clickable, but the text is obsolete, and it isn't intuitive to press it.

**Comment by kaaholst** [comment]
I have released a new beta version 2.0.0-beta-3 which discovers the port number along with the server address, so it is no longer necessary to manually input the port, and hopefully we will see no more of these port related connection issues.
Thanks for your help resolving this issue.
