### ISSUE TITLE
No screen setting in V2.0.1

### ISSUE THREAD

**Issue by Toonuser** [nikclayton/android-squeezer#630]
Using V2.0.1... Within Settings there is no longer a 'Screen' sub menu, which would allow me to set Albumview to Small artwork. Now am stuck with the tiles view, so had to roll back to V2.0.0.
Many thanks for all your efforts!

**Comment by kaaholst** [comment]
The Settings/Screen item has been removed in 2.0.1 because it caused confusion that App settings were mixed in with player and server settings.
Items from Screen has been moved to other places. Artwork settings is now changed with a button on the top bar and Theme is set via the options menu (the 3-dot button in the top bar) and then Settings.
Nothing which was in Screen has been removed from Squeezer.
