### ISSUE TITLE
Organize the playlist

### ISSUE THREAD

**Issue by lim-on-air** [nikclayton/android-squeezer#631]
Hi, 

A functionnality I can't find in the new version is the possibility to organize the playlist (move up or down the tracks). Where is it ?

**Comment by kaaholst** [comment]
This is currently not possible, it's on the road map

**Comment by St3C0m** [comment]
This is a feature request I was going to add as well. It would be great if all tracks within the active playlist were displayed with a drag handle on the left side so that they could be dragged up or down to relocate them within the list. Similar functionality to that within the LMS web interface that allows you to move tracks up and down the playlist by dragging them. Looking forward to this being implemented in future versions. Keep up the good work, Squeezer is awesome! 👍🙂

**Comment by kaaholst** [comment]
Possibility to organize the playlist is under active development, will be available in the next version.

**Comment by kaaholst** [comment]
This is available in Squeezer version 2.2.1 and newer, closing.
