### ISSUE TITLE
Album scroll changes from covers to list

### ISSUE THREAD

**Issue by josh308** [nikclayton/android-squeezer#635]
When I select the Album option in my music, I get a grid of album cover images.  This is great and just what I want. But if I scroll the screen down to the end, the cover images disappear and the screen changes to a text list. Can't switch it back to images...have to go back to home screen and start again. Can
 it be fixed so that the cover images stay ?

**Comment by kaaholst** [comment]
You are right that is a bug. It is fixed in the version, 2.1.0, which is going into beta now. If you like to see it before it is released, you can opt in  to beta here: https://play.google.com/apps/testing/uk.org.ngo.squeezer.
If you do not wish to opt in, please be patient until the official version is released.

**Comment by kaaholst** [comment]
Fixed in 2.1.0
