### ISSUE TITLE
Not connecting to server anymore

### ISSUE THREAD

**Issue by Bladdicus** [nikclayton/android-squeezer#637]
v2.0.1 on a Pixel 4. Squeezer suddenly lost contact with the server and won't find it anymore. I'm using the same static IP I've had for years- no changes to the Win 10 machine that serves. Squeezer is also not seeing the player. I've rebooted everything (router, box, server, phone....) to no avail. Any ideas?

**Comment by kaaholst** [comment]
I am not able to tell from the description what the problem is, but I have a few questions to help pinpoint the problem.

1. Can you connect to LMS from the browser on the same device you run Squeezer (probably your phone)?
2. What is the ip address of your phone (system settings/wifi/menu/advanced)?
3. What is the ip address of LMS?
4. What is the Web Server Port Number port of LMS (on the LMS Web-Interface settings/advanced/network)
5. What is the result of running a scan for servers from squeezer?

**Comment by Bladdicus** [comment]
Strangest thing, it started working again this morning. I have no idea what changed. Thanks for responding!
