### ISSUE TITLE
Connection between squeezer ans LMS is lost when squeezer is out of focus

### ISSUE THREAD

**Issue by smirkomix** [nikclayton/android-squeezer#638]
Hi,
with the new code base I recognized that quite often after some action was done in squeezer and another app on the phone is used or the phone is set to standby and then squeezer is called again the connection to the LMS is lost.
This behaviour was present in the earlier version also sometimes but with the rewritten code it happens far to often. A click on connect solves the problem but this is annoying.

Phone: Honor 9 with Android 9 and Squeezer 2.0.1
LMS 7.9.2 running on Debian 

Thanks and kind regards
Ulf

**Comment by kaaholst** [comment]
I am not able to reproduce this. Before version 1.5.3 (Oct. 19), this could happen. Since then android should not be able to close the Squeezers connection (hence the requirement that we always show a non dismissible notification). 
Perhaps a battery savings option in the phone settings is causing this?

**Comment by smirkomix** [comment]
Thanks for this hint. I changed the battery saving setting on my phone from auto to manual with the three subentries to "on" and now the connection to the LMS is very stable.
Regards
Ulf
