### ISSUE TITLE
Home screen widget gives player not found toast frequently

### ISSUE THREAD

**Issue by idontusenumbers** [nikclayton/android-squeezer#645]
- If squeezer service hasn't connected to LMS, tapping the widgets just gives player not found toast
  - Should probably open squeezer to display connection screen instead
- If squeezer service isn't started, the first tap on the widget launches the service then displays toast error; second tap works fine
  - Should probably wait for service to start

**Comment by kaaholst** [comment]
Yes that's right.

Do you want me to look into it, or would you rather do it yourself?

Also it could be considered what to do if the selected player is controlled by another server than the one Squeezer is currently configured to. E.g because there multiple servers at one location or servers at different locations. The current action is to display player not found toast. This is maybe the proper thing to do?

**Comment by idontusenumbers** [comment]
I suspect multiple servers is pretty unusual; I suspect the best outcome would be squeezer service is launched and connects to the server the player is on for which the widget is controlling. The widget code would need to be updated to store the server information along with the player. I suspect we could add the player name as well so the toasts are more user friendly.

Coordinating the service and connectivity is on the fringe of my comfort level. Although I feel bad tossing the widget in in a buggy state and asking for you to take over.

**Comment by kaaholst** [comment]
@idontusenumbers  I wanted to look into this, but I can't reproduce item no 2. 
Do you know how to reliably trigger this?

**Comment by kaaholst** [comment]
This is now ready in the develop branch.
While at it I changed to localized Player Not Found toasts, and added shortcuts for the Now Playing and Current Playlist screens.
